In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("IMDB Dataset.csv")

In [3]:
df.shape

(50000, 2)

In [4]:
df.head(5)

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [5]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [6]:
df.drop_duplicates(inplace=True)

In [7]:
df.shape

(49582, 2)

## Text pre-processing

### Regex (Regular Expression) library is used for Text pre-processing

#### Step 1 - Lowercase conversion

In [8]:
df["review"]=df["review"].str.lower()

### Step 2 - Remove URLs

In [9]:
import re

def remove_urls(text):
    text=re.sub(r"http\S+","",text)
    return text

df["review"]=df["review"].apply(remove_urls)

### Step3 - Remove Punctuations

In [10]:
def remove_punctuations(text):
    text=re.sub(r"[^A-Z-a-z-0-9\s]","",text)
    return text


df["review"]=df["review"].apply(remove_punctuations)

### Step4 - Remove HTML Tags

In [11]:
def remove_tags(text):
    text=re.sub(r"<.*?>","",text)
    return text

df["review"]=df["review"].apply(remove_tags)

### Step5 - Removing Stopwords

In [12]:
import nltk

nltk.download("punkt") #for tokenization
nltk.download("punkt_tab")
nltk.download("stopwords")

from nltk.tokenize import word_tokenize #Token creation
from nltk.corpus import stopwords #pre-defined stopwords of English language

[nltk_data] Downloading package punkt to /Users/aksha/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /Users/aksha/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to /Users/aksha/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [13]:
def remove_stopwords(text):
    tokens=word_tokenize(text)
    stop_words=stopwords.words("english")

    for word in tokens:
        if word in stop_words:
            text=text.replace(word,"")
    return text

df["review"]=df["review"].apply(remove_stopwords)

In [15]:
df.head()

                                              review sentiment
0  e    revewers  nted   wtchg  1 oz epode ll  ho...  positive
1   wderful ltle producti br br  filming techniqu...  positive
2   thought ths   wderful wy  spend tme   o hot s...  positive
3  bsclly res  fmly   lttle boy jke thks res  zom...  negative
4  petter mtte love   time  mey   vully stunng fi...  positive

### Step6 - Stemming

In [16]:
from nltk.stem import PorterStemmer

def stemming(text):
    ps=PorterStemmer()
    stemmed_words=[]

    for token in word_tokenize(text):
        stemmed_token=ps.stem(token)
        stemmed_words.append(stemmed_token)

    return " ".join(stemmed_words)

df["review"]=df["review"].apply(stemming)

In [17]:
df.head()

                                              review sentiment
0  e revew nted wtchg 1 oz epod ll hook y rght ex...  positive
1  wder ltle producti br br film techniqu unssumi...  positive
2  thought th wder wy spend tme o hot summer week...  positive
3  bsclli re fmli lttle boy jke thk re zomb close...  negative
4  petter mtte love time mey vulli stunng film wt...  positive

### Encoding the sentiment (target)

In [19]:
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()

df["sentiment"]=le.fit_transform(df["sentiment"])

In [20]:
y=df["sentiment"]

y

0        1
1        1
2        1
3        0
4        1
        ..
49995    1
49996    0
49997    0
49998    0
49999    0
Name: sentiment, Length: 49582, dtype: int64

### Vectorization

In [27]:
from sklearn.feature_extraction.text import TfidfVectorizer

tf=TfidfVectorizer(max_features=5000)

X=tf.fit_transform(df["review"])

In [28]:
print(X)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 4127862 stored elements and shape (49582, 5000)>
  Coords	Values
  (0, 3534)	0.05569839639885624
  (0, 2875)	0.09438890510917901
  (0, 4940)	0.11568160991904046
  (0, 3006)	0.47508036402355336
  (0, 1280)	0.1370952953561258
  (0, 2291)	0.049554702424131604
  (0, 1931)	0.07966376257469433
  (0, 3546)	0.09697873087310795
  (0, 1366)	0.062254300731944094
  (0, 1961)	0.06216477650615386
  (0, 220)	0.08665881431306528
  (0, 1621)	0.07422135765862845
  (0, 4366)	0.042367009596884504
  (0, 4168)	0.17856073935930092
  (0, 3691)	0.03381062382469526
  (0, 4737)	0.27051290938118355
  (0, 3803)	0.04424136037454803
  (0, 4769)	0.058925075441998466
  (0, 1740)	0.03764681049966722
  (0, 4495)	0.07683034350119061
  (0, 3854)	0.17675188607887948
  (0, 1631)	0.06126846522210289
  (0, 1861)	0.07185010010895893
  (0, 3329)	0.06461867548962605
  (0, 3332)	0.08440797774273125
  :	:
  (49581, 4891)	0.10705250755821397
  (49581, 1542)	0.17602315236720653
  (49581, 4492)	0.09396092144849935
  (49581, 438)	0.11272615467679627
  (49581, 4274)	0.10936258396840304
  (49581, 1956)	0.1002258516475625
  (49581, 560)	0.08444699133916567
  (49581, 2187)	0.13947476414517454
  (49581, 2218)	0.09519208310453069
  (49581, 4344)	0.17545238036473318
  (49581, 4630)	0.11606051531824249
  (49581, 3644)	0.08553483436872913
  (49581, 4734)	0.1238473768677231
  (49581, 1974)	0.12828788111430026
  (49581, 532)	0.12478130304531058
  (49581, 2625)	0.1740832293101233
  (49581, 4456)	0.16032779949513903
  (49581, 2174)	0.19040924675187484
  (49581, 4032)	0.20160530922868816
  (49581, 344)	0.14715486104747103
  (49581, 2701)	0.1746829378886495
  (49581, 445)	0.13338362747087637
  (49581, 4980)	0.15104032817743804
  (49581, 1765)	0.1577396315531798
  (49581, 3487)	0.15172668643393847